POST http://localhost:8180/auth/realms/homekeep/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=homekeep-app&username=niko&password=Meranmor13&grant_type=password&client_secret=4430f5f0-a9bf-4e7f-b6fa-90d135f72f88

###
