POST http://localhost:8180/auth/realms/homekeep/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=homekeep-app&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkNTQyYzRjZS0yYzkxLTQ0ZmMtYjg3My00M2NiNWFlMDllN2QifQ.eyJleHAiOjE1OTE1Mjc0NjQsImlhdCI6MTU5MTUyNTY2NCwianRpIjoiYzJiMDkyMDYtNTQ0MS00ODQ2LThiM2MtMThkMTFkY2U2MjAzIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2hvbWVrZWVwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2hvbWVrZWVwIiwic3ViIjoiMzE3MmMwMTItNWZkNy00MjM0LWFjYzUtMGYyYTBhZDAzMDY0IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImhvbWVrZWVwLWFwcCIsInNlc3Npb25fc3RhdGUiOiIyZjE0ZWFmNi02ZTE3LTQ0NTMtODhhMC1hMTY3NmU3M2U1NWEiLCJzY29wZSI6InByb2ZpbGUgZW1haWwifQ.i4UXirxhYpmoVzevVfpouungQZ3ZU9Z9OHhZRsKYsuU&grant_type=refresh_token

###
